# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\text.c\pythonwork\ui\window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("客户端")
        self.color=QtGui.QColor("#87CEFA")
        MainWindow.resize(700, 500)
        MainWindow.setMinimumSize(QtCore.QSize(700, 500))
        MainWindow.setMaximumSize(QtCore.QSize(700, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-1, -1, 701, 381))
        self.widget.setObjectName("widget")
        self.user = QtWidgets.QLabel(self.widget)
        self.user.setGeometry(QtCore.QRect(110, 10, 121, 41))
        self.user.setObjectName("user")
        self.information = QtWidgets.QTextEdit(self.widget)
        self.information.setGeometry(QtCore.QRect(10, 60, 681, 331))
        self.information.setObjectName("information")
        self.information.setReadOnly(True)
        self.name = QtWidgets.QLabel(self.widget)
        self.name.setGeometry(QtCore.QRect(20, 10, 54, 41))
        self.name.setObjectName("name")
        self.btn_color = QtWidgets.QPushButton(self.centralwidget)
        self.btn_color.setGeometry(QtCore.QRect(140, 450, 111, 31))
        self.btn_color.setStyleSheet("QPushButton{ border-radius: 6;color: white;background-color: #34495e;}\n"
"QPushButton:pressed{ border-radius: 6;color: white;background-color: #517382;}\n"
"")
        self.btn_color.setObjectName("btn_color")
        self.btn_emoij = QtWidgets.QPushButton(self.centralwidget)
        self.btn_emoij.setGeometry(QtCore.QRect(280, 450, 111, 31))
        self.btn_emoij.setStyleSheet("QPushButton{ border-radius: 6;color: white;background-color: #34495e;}\n"
"QPushButton:pressed{ border-radius: 6;color: white;background-color: #517382;}\n"
"")
        self.btn_emoij.setObjectName("btn_emoij")
        self.btn_file = QtWidgets.QPushButton(self.centralwidget)
        self.btn_file.setGeometry(QtCore.QRect(420, 450, 111, 31))
        self.btn_file.setStyleSheet("QPushButton{ border-radius: 6;color: white;background-color: #34495e;}\n"
"QPushButton:pressed{ border-radius: 6;color: white;background-color: #517382;}\n"
"")
        self.btn_file.setObjectName("btn_file")
        self.btn_echo = QtWidgets.QPushButton(self.centralwidget)
        self.btn_echo.setGeometry(QtCore.QRect(20, 450, 91, 31))
        self.btn_echo.setStyleSheet("QPushButton{ border-radius: 6;color: white;background-color: #34495e;}\n"
"QPushButton:pressed{ border-radius: 6;color: white;background-color: #517382;}\n"
"")
        self.btn_echo.setObjectName("btn_echo")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(569, 450, 111, 31))
        self.pushButton.setStyleSheet("QPushButton{ border-radius: 6;color: white;background-color: #34495e;}\n"
"QPushButton:pressed{ border-radius: 6;color: white;background-color: #517382;}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit.setGeometry(QtCore.QRect(579, 10, 101, 31))
        self.btn_exit.setStyleSheet("QPushButton{ border-radius: 6;color: white;background-color: #34495e;}\n"
"QPushButton:pressed{ border-radius: 6;color: white;background-color: #517382;}\n"
"")
        self.btn_exit.setObjectName("btn_exit")
        self.btn_sent = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sent.setGeometry(QtCore.QRect(570, 400, 111, 31))
        self.btn_sent.setStyleSheet("QPushButton{ border-radius: 6;color: white;background-color: #34495e;}\n"
"QPushButton:pressed{ border-radius: 6;color: white;background-color: #517382;}\n"
"")
        self.btn_sent.setObjectName("btn_sent")
        self.input = QtWidgets.QLineEdit(self.centralwidget)
        self.input.setGeometry(QtCore.QRect(20, 402, 511, 31))
        self.input.setStyleSheet("QLineEdit{border-radius: 6;border: 2px solid #bdc3c7;height:22;}")
        self.input.setObjectName("input")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.input.setFocus()
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "客户端"))
        self.user.setText(_translate("MainWindow", "用户名："))
        self.name.setText(_translate("MainWindow", "欢迎"))
        self.btn_color.setText(_translate("MainWindow", "颜色"))
        self.btn_emoij.setText(_translate("MainWindow", "表情"))
        self.btn_file.setText(_translate("MainWindow", "选择文件"))
        self.btn_echo.setText(_translate("MainWindow", "文件接收"))
        self.pushButton.setText(_translate("MainWindow", "用户列表"))
        self.btn_exit.setText(_translate("MainWindow", "退出登录"))
        self.btn_sent.setText(_translate("MainWindow", "发送"))