# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\text.c\pythonwork\ui\emoji.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
import os


class Ui_Form(object):
    def setupUi(self, Form,bs):
        self.bs = bs
        self.emojm = {"btn_11":"\emoji-11.png","btn_12":"\emoji-12.png","btn_13":"\emoji-13.png","btn_14":"\emoji-14.png",
                      "btn_15":"\emoji-15.png","btn_21":"\emoji-21.png","btn_22":"\emoji-22.png","btn_23":"\emoji-23.png",
                      "btn_24":"\emoji-24.png","btn_25":"\emoji-25.png","btn_31":"\emoji-31.png","btn_32":"\emoji-32.png",
                      "btn_33":"\emoji-33.png","btn_34":"\emoji-34.png","btn_35":"\emoji-35.png"}
        Form.setObjectName("Emoji")
        Form.resize(1019, 860)
        Form.setMinimumSize(QtCore.QSize(1019, 860))
        Form.setMaximumSize(QtCore.QSize(1019, 860))
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 10, 1001, 781))
        self.widget.setObjectName("widget")
        self.lb_11 = QtWidgets.QLabel(self.widget)
        self.lb_11.setGeometry(QtCore.QRect(0, 0, 201, 211))
        self.lb_11.setText("")
        self.lb_11.setPixmap(QtGui.QPixmap("f:\\text.c\\pythonwork\\ui\\../sqr/emoji-11.png"))
        self.lb_11.setObjectName("lb_11")
        self.lb_12 = QtWidgets.QLabel(self.widget)
        self.lb_12.setGeometry(QtCore.QRect(200, 0, 201, 211))
        self.lb_12.setText("")
        self.lb_12.setPixmap(QtGui.QPixmap("f:\\text.c\\pythonwork\\ui\\../sqr/emoji-12.png"))
        self.lb_12.setObjectName("lb_12")
        self.lb_13 = QtWidgets.QLabel(self.widget)
        self.lb_13.setGeometry(QtCore.QRect(393, 0, 201, 211))
        self.lb_13.setText("")
        self.lb_13.setPixmap(QtGui.QPixmap("f:\\text.c\\pythonwork\\ui\\../sqr/emoji-13.png"))
        self.lb_13.setObjectName("lb_13")
        self.lb_14 = QtWidgets.QLabel(self.widget)
        self.lb_14.setGeometry(QtCore.QRect(590, 0, 201, 211))
        self.lb_14.setText("")
        self.lb_14.setPixmap(QtGui.QPixmap("f:\\text.c\\pythonwork\\ui\\../sqr/emoji-14.png"))
        self.lb_14.setObjectName("lb_14")
        self.lb_15 = QtWidgets.QLabel(self.widget)
        self.lb_15.setGeometry(QtCore.QRect(800, 0, 201, 211))
        self.lb_15.setText("")
        self.lb_15.setPixmap(QtGui.QPixmap("f:\\text.c\\pythonwork\\ui\\../sqr/emoji-15.png"))
        self.lb_15.setObjectName("lb_15")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(0, 210, 1001, 51))
        self.widget_2.setObjectName("widget_2")
        self.btn_11 = QtWidgets.QPushButton(self.widget_2)
        self.btn_11.setGeometry(QtCore.QRect(50, 10, 101, 31))
        self.btn_11.setStyleSheet("QPushButton{ border-radius: 6;color: white;background-color: #34495e;}\n"
"QPushButton:pressed{ border-radius: 6;color: white;background-color: #517382;}\n"
"")
        self.btn_11.setObjectName("btn_11")
        self.btn_12 = QtWidgets.QPushButton(self.widget_2)
        self.btn_12.setGeometry(QtCore.QRect(250, 10, 101, 31))
        self.btn_12.setStyleSheet("QPushButton{ border-radius: 6;color: white;background-color: #34495e;}\n"
"QPushButton:pressed{ border-radius: 6;color: white;background-color: #517382;}\n"
"")
        self.btn_12.setObjectName("btn_12")
        self.btn_13 = QtWidgets.QPushButton(self.widget_2)
        self.btn_13.setGeometry(QtCore.QRect(440, 10, 101, 31))
        self.btn_13.setStyleSheet("QPushButton{ border-radius: 6;color: white;background-color: #34495e;}\n"
"QPushButton:pressed{ border-radius: 6;color: white;background-color: #517382;}\n"
"")
        self.btn_13.setObjectName("btn_13")
        self.btn_14 = QtWidgets.QPushButton(self.widget_2)
        self.btn_14.setGeometry(QtCore.QRect(640, 10, 101, 31))
        self.btn_14.setStyleSheet("QPushButton{ border-radius: 6;color: white;background-color: #34495e;}\n"
"QPushButton:pressed{ border-radius: 6;color: white;background-color: #517382;}\n"
"")
        self.btn_14.setObjectName("btn_14")
        self.btn_15 = QtWidgets.QPushButton(self.widget_2)
        self.btn_15.setGeometry(QtCore.QRect(859, 10, 101, 31))
        self.btn_15.setStyleSheet("QPushButton{ border-radius: 6;color: white;background-color: #34495e;}\n"
"QPushButton:pressed{ border-radius: 6;color: white;background-color: #517382;}\n"
"")
        self.btn_15.setObjectName("btn_15")
        self.lb_21 = QtWidgets.QLabel(self.widget)
        self.lb_21.setGeometry(QtCore.QRect(0, 265, 201, 211))
        self.lb_21.setText("")
        self.lb_21.setPixmap(QtGui.QPixmap("f:\\text.c\\pythonwork\\ui\\../sqr/emoji-21.png"))
        self.lb_21.setObjectName("lb_21")
        self.lb_22 = QtWidgets.QLabel(self.widget)
        self.lb_22.setGeometry(QtCore.QRect(200, 260, 201, 211))
        self.lb_22.setText("")
        self.lb_22.setPixmap(QtGui.QPixmap("f:\\text.c\\pythonwork\\ui\\../sqr/emoji-22.png"))
        self.lb_22.setObjectName("lb_22")
        self.lb_23 = QtWidgets.QLabel(self.widget)
        self.lb_23.setGeometry(QtCore.QRect(400, 260, 201, 211))
        self.lb_23.setText("")
        self.lb_23.setPixmap(QtGui.QPixmap("f:\\text.c\\pythonwork\\ui\\../sqr/emoji-23.png"))
        self.lb_23.setObjectName("lb_23")
        self.lb_24 = QtWidgets.QLabel(self.widget)
        self.lb_24.setGeometry(QtCore.QRect(600, 260, 201, 211))
        self.lb_24.setText("")
        self.lb_24.setPixmap(QtGui.QPixmap("f:\\text.c\\pythonwork\\ui\\../sqr/emoji-24.png"))
        self.lb_24.setObjectName("lb_24")
        self.lb_25 = QtWidgets.QLabel(self.widget)
        self.lb_25.setGeometry(QtCore.QRect(800, 260, 201, 211))
        self.lb_25.setText("")
        self.lb_25.setPixmap(QtGui.QPixmap("f:\\text.c\\pythonwork\\ui\\../sqr/emoji-25.png"))
        self.lb_25.setObjectName("lb_25")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setGeometry(QtCore.QRect(0, 470, 1001, 51))
        self.widget_3.setObjectName("widget_3")
        self.btn_21 = QtWidgets.QPushButton(self.widget_3)
        self.btn_21.setGeometry(QtCore.QRect(50, 10, 101, 31))
        self.btn_21.setStyleSheet("QPushButton{ border-radius: 6;color: white;background-color: #34495e;}\n"
"QPushButton:pressed{ border-radius: 6;color: white;background-color: #517382;}\n"
"")
        self.btn_21.setObjectName("btn_21")
        self.btn_22 = QtWidgets.QPushButton(self.widget_3)
        self.btn_22.setGeometry(QtCore.QRect(250, 10, 101, 31))
        self.btn_22.setStyleSheet("QPushButton{ border-radius: 6;color: white;background-color: #34495e;}\n"
"QPushButton:pressed{ border-radius: 6;color: white;background-color: #517382;}\n"
"")
        self.btn_22.setObjectName("btn_22")
        self.btn_23 = QtWidgets.QPushButton(self.widget_3)
        self.btn_23.setGeometry(QtCore.QRect(440, 10, 101, 31))
        self.btn_23.setStyleSheet("QPushButton{ border-radius: 6;color: white;background-color: #34495e;}\n"
"QPushButton:pressed{ border-radius: 6;color: white;background-color: #517382;}\n"
"")
        self.btn_23.setObjectName("btn_23")
        self.btn_24 = QtWidgets.QPushButton(self.widget_3)
        self.btn_24.setGeometry(QtCore.QRect(640, 10, 101, 31))
        self.btn_24.setStyleSheet("QPushButton{ border-radius: 6;color: white;background-color: #34495e;}\n"
"QPushButton:pressed{ border-radius: 6;color: white;background-color: #517382;}\n"
"")
        self.btn_24.setObjectName("btn_24")
        self.btn_25 = QtWidgets.QPushButton(self.widget_3)
        self.btn_25.setGeometry(QtCore.QRect(859, 10, 101, 31))
        self.btn_25.setStyleSheet("QPushButton{ border-radius: 6;color: white;background-color: #34495e;}\n"
"QPushButton:pressed{ border-radius: 6;color: white;background-color: #517382;}\n"
"")
        self.btn_25.setObjectName("btn_25")
        self.lb_31 = QtWidgets.QLabel(self.widget)
        self.lb_31.setGeometry(QtCore.QRect(0, 520, 201, 211))
        self.lb_31.setText("")
        self.lb_31.setPixmap(QtGui.QPixmap("f:\\text.c\\pythonwork\\ui\\../sqr/emoji-31.png"))
        self.lb_31.setObjectName("lb_31")
        self.lb_32 = QtWidgets.QLabel(self.widget)
        self.lb_32.setGeometry(QtCore.QRect(200, 520, 201, 211))
        self.lb_32.setText("")
        self.lb_32.setPixmap(QtGui.QPixmap("f:\\text.c\\pythonwork\\ui\\../sqr/emoji-32.png"))
        self.lb_32.setObjectName("lb_32")
        self.lb_33 = QtWidgets.QLabel(self.widget)
        self.lb_33.setGeometry(QtCore.QRect(400, 520, 201, 211))
        self.lb_33.setText("")
        self.lb_33.setPixmap(QtGui.QPixmap("f:\\text.c\\pythonwork\\ui\\../sqr/emoji-33.png"))
        self.lb_33.setObjectName("lb_33")
        self.lb_34 = QtWidgets.QLabel(self.widget)
        self.lb_34.setGeometry(QtCore.QRect(600, 520, 201, 211))
        self.lb_34.setText("")
        self.lb_34.setPixmap(QtGui.QPixmap("f:\\text.c\\pythonwork\\ui\\../sqr/emoji-34.png"))
        self.lb_34.setObjectName("lb_34")
        self.lb_35 = QtWidgets.QLabel(self.widget)
        self.lb_35.setGeometry(QtCore.QRect(800, 520, 201, 211))
        self.lb_35.setText("")
        self.lb_35.setPixmap(QtGui.QPixmap("f:\\text.c\\pythonwork\\ui\\../sqr/emoji-35.png"))
        self.lb_35.setObjectName("lb_35")
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setGeometry(QtCore.QRect(0, 730, 1001, 51))
        self.widget_4.setObjectName("widget_4")
        self.btn_31 = QtWidgets.QPushButton(self.widget_4)
        self.btn_31.setGeometry(QtCore.QRect(50, 10, 101, 31))
        self.btn_31.setStyleSheet("QPushButton{ border-radius: 6;color: white;background-color: #34495e;}\n"
"QPushButton:pressed{ border-radius: 6;color: white;background-color: #517382;}\n"
"")
        self.btn_31.setObjectName("btn_31")
        self.btn_32 = QtWidgets.QPushButton(self.widget_4)
        self.btn_32.setGeometry(QtCore.QRect(250, 10, 101, 31))
        self.btn_32.setStyleSheet("QPushButton{ border-radius: 6;color: white;background-color: #34495e;}\n"
"QPushButton:pressed{ border-radius: 6;color: white;background-color: #517382;}\n"
"")
        self.btn_32.setObjectName("btn_32")
        self.btn_33 = QtWidgets.QPushButton(self.widget_4)
        self.btn_33.setGeometry(QtCore.QRect(440, 10, 101, 31))
        self.btn_33.setStyleSheet("QPushButton{ border-radius: 6;color: white;background-color: #34495e;}\n"
"QPushButton:pressed{ border-radius: 6;color: white;background-color: #517382;}\n"
"")
        self.btn_33.setObjectName("btn_33")
        self.btn_34 = QtWidgets.QPushButton(self.widget_4)
        self.btn_34.setGeometry(QtCore.QRect(640, 10, 101, 31))
        self.btn_34.setStyleSheet("QPushButton{ border-radius: 6;color: white;background-color: #34495e;}\n"
"QPushButton:pressed{ border-radius: 6;color: white;background-color: #517382;}\n"
"")
        self.btn_34.setObjectName("btn_34")
        self.btn_35 = QtWidgets.QPushButton(self.widget_4)
        self.btn_35.setGeometry(QtCore.QRect(859, 10, 101, 31))
        self.btn_35.setStyleSheet("QPushButton{ border-radius: 6;color: white;background-color: #34495e;}\n"
"QPushButton:pressed{ border-radius: 6;color: white;background-color: #517382;}\n"
"")
        self.btn_35.setObjectName("btn_35")
        self.widget_5 = QtWidgets.QWidget(Form)
        self.widget_5.setGeometry(QtCore.QRect(10, 800, 1001, 51))
        self.widget_5.setObjectName("widget_5")
        self.btn_browse = QtWidgets.QPushButton(self.widget_5)
        self.btn_browse.setGeometry(QtCore.QRect(640, 10, 101, 31))
        self.btn_browse.setStyleSheet("QPushButton{ border-radius: 6;color: white;background-color: #34495e;}\n"
"QPushButton:pressed{ border-radius: 6;color: white;background-color: #517382;}\n"
"")
        self.btn_browse.setObjectName("btn_browse")
        self.lineEdit = QtWidgets.QLineEdit(self.widget_5)
        self.lineEdit.setGeometry(QtCore.QRect(250, 10, 341, 31))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        '''槽函数连接'''
        self.btn_11.clicked.connect(lambda: self.emojis("btn_11"))
        self.btn_12.clicked.connect(lambda: self.emojis("btn_12"))
        self.btn_13.clicked.connect(lambda: self.emojis("btn_13"))
        self.btn_14.clicked.connect(lambda: self.emojis("btn_14"))
        self.btn_15.clicked.connect(lambda: self.emojis("btn_15"))
        self.btn_21.clicked.connect(lambda: self.emojis("btn_21"))
        self.btn_22.clicked.connect(lambda: self.emojis("btn_22"))
        self.btn_23.clicked.connect(lambda: self.emojis("btn_23"))
        self.btn_24.clicked.connect(lambda: self.emojis("btn_24"))
        self.btn_25.clicked.connect(lambda: self.emojis("btn_25"))
        self.btn_31.clicked.connect(lambda: self.emojis("btn_31"))
        self.btn_32.clicked.connect(lambda: self.emojis("btn_32"))
        self.btn_33.clicked.connect(lambda: self.emojis("btn_33"))
        self.btn_34.clicked.connect(lambda: self.emojis("btn_34"))
        self.btn_35.clicked.connect(lambda: self.emojis("btn_35"))

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Emoji"))
        self.btn_11.setText(_translate("Form", "选择"))
        self.btn_12.setText(_translate("Form", "选择"))
        self.btn_13.setText(_translate("Form", "选择"))
        self.btn_14.setText(_translate("Form", "选择"))
        self.btn_15.setText(_translate("Form", "选择"))
        self.btn_21.setText(_translate("Form", "选择"))
        self.btn_22.setText(_translate("Form", "选择"))
        self.btn_23.setText(_translate("Form", "选择"))
        self.btn_24.setText(_translate("Form", "选择"))
        self.btn_25.setText(_translate("Form", "选择"))
        self.btn_31.setText(_translate("Form", "选择"))
        self.btn_32.setText(_translate("Form", "选择"))
        self.btn_33.setText(_translate("Form", "选择"))
        self.btn_34.setText(_translate("Form", "选择"))
        self.btn_35.setText(_translate("Form", "选择"))
    def getpath(self):#获取当前文件中表情目录
        path_a = os.getcwd()
        path = path_a+"\sqr"
        return path
    def emojis(self,text,color=QtGui.QColor("#87CEFA")):
        cursor = self.bs.information.textCursor()
        cursor.movePosition(QtGui.QTextCursor.End)
        back_format = QtGui.QTextBlockFormat()
        back_format.setAlignment(QtCore.Qt.AlignRight)
        cursor.mergeBlockFormat(back_format)
        if text !="":
                path = self.getpath()#获取当前路径
                path += self.emojm[text]#设置对应图片的绝对路径
                image_html = '<img src="%s" />' % path#设置html格式文字
                cursor.insertText("\n")
                self.bs.information.insertHtml(image_html)#显示在自己屏幕上
                cursor.insertText("\n")
        self.bs.information.setTextCursor(cursor)
        texts = "emoj"+self.bs.color_string+image_html
        texts.encode("utf-8")
        try:
            self.bs.SendStr(texts)#以emoj的形式发送文件路径
        except:
            self.bs.SendStr(texts)
