# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\text.c\pythonwork\ui\file.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow,father):
        self.MainWindow = MainWindow
        self.MainWindow.setObjectName("MainWindow")
        self.MainWindow.resize(670, 500)
        self.MainWindow.setMinimumSize(QtCore.QSize(554, 432))
        self.MainWindow.setMaximumSize(QtCore.QSize(682, 900))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.file_name = QtWidgets.QTextEdit(self.centralwidget)
        self.file_name.setGeometry(QtCore.QRect(10, 60, 361, 361))
        self.file_name.setObjectName("file_name")
        self.file_save_path = QtWidgets.QTextEdit(self.centralwidget)
        self.file_save_path.setGeometry(QtCore.QRect(400, 60, 251, 361))
        self.file_save_path.setObjectName("file_save_path")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(13, 6, 641, 41))
        self.title.setScaledContents(False)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.btn_path = QtWidgets.QPushButton(self.centralwidget)
        self.btn_path.setGeometry(QtCore.QRect(450, 440, 161, 41))
        self.btn_path.setStyleSheet("QPushButton{ border-radius: 6;color: white;background-color: #34495e;}\n"
"QPushButton:pressed{ border-radius: 6;color: white;background-color: #517382;}")
        self.btn_path.setObjectName("btn_path")
        self.true_file_path = QtWidgets.QLineEdit(self.centralwidget)
        self.true_file_path.setGeometry(QtCore.QRect(40, 440, 381, 41))
        self.true_file_path.setStyleSheet("QLineEdit{border-radius: 6;border: 2px solid #bdc3c7;height:22;}")
        self.true_file_path.setObjectName("true_file_path")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.father = father
        self.true_path = self.father.path
        self.true_file_path.setText(self.true_path)
        self.file_name.setReadOnly(True)
        self.file_save_path.setReadOnly(True)
        self.btn_path.clicked.connect(self.chose_fileptah)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "文件"))
        self.file_name.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">文件名</p></body></html>"))
        self.file_save_path.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">存储地址</p></body></html>"))
        self.title.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">文件接收柜</span></p></body></html>"))
        self.btn_path.setText(_translate("MainWindow", "浏览"))
    def chose_fileptah(self):
        options = QFileDialog.Options()
        options |= QFileDialog.DontUseNativeDialog
        folder_path = QFileDialog.getExistingDirectory(self.MainWindow,"Select Folder",self.true_path,options=options)
        if folder_path:
            self.true_path = folder_path + "/"#获取选择的地址
            self.true_file_path.setText(self.true_path)
            self.father.path = self.true_path#更新其父类的地址