# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\text.c\pythonwork\ui\server.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox,QFileDialog,QColorDialog
import Ui_emoji
import sys
import os
import csv


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("服务端")
        self.color=QtGui.QColor("#87CEFA")
        Dialog.resize(830, 579)
        Dialog.setMaximumSize(QtCore.QSize(830, 579))
        Dialog.setMinimumSize(QtCore.QSize(830, 579))
        self.userlist = QtWidgets.QTextEdit(Dialog)
        self.userlist.setGeometry(QtCore.QRect(10, 30, 141, 401))
        self.userlist.setObjectName("userlist")
        self.userlist.setReadOnly(True)
        self.btn_close = QtWidgets.QPushButton(Dialog)
        self.btn_close.setGeometry(QtCore.QRect(10, 450, 131, 41))
        self.btn_close.setStyleSheet("QPushButton{ border-radius: 6;color: white;background-color: #34495e;}\n"
"QPushButton:pressed{ border-radius: 6;color: white;background-color: #517382;}")
        self.btn_close.setObjectName("btn_close")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 141, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.information = QtWidgets.QTextEdit(Dialog)
        self.information.setGeometry(QtCore.QRect(160, 60, 661, 371))
        self.information.setObjectName("information")
        self.information.setReadOnly(True)
        self.btn_sent = QtWidgets.QPushButton(Dialog)
        self.btn_sent.setGeometry(QtCore.QRect(710, 450, 101, 41))
        self.btn_sent.setStyleSheet("QPushButton{ border-radius: 6;color: white;background-color: #34495e;}\n"
"QPushButton:pressed{ border-radius: 6;color: white;background-color: #517382;}")
        self.btn_sent.setObjectName("btn_sent")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(170, 450, 521, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.btn_del = QtWidgets.QPushButton(Dialog)
        self.btn_del.setGeometry(QtCore.QRect(9, 520, 131, 41))
        self.btn_del.setStyleSheet("QPushButton{ border-radius: 6;color: white;background-color: #34495e;}\n"
"QPushButton:pressed{ border-radius: 6;color: white;background-color: #517382;}")
        self.btn_del.setObjectName("btn_del")
        self.btn_echo = QtWidgets.QPushButton(Dialog)
        self.btn_echo.setGeometry(QtCore.QRect(710, 520, 101, 41))
        self.btn_echo.setStyleSheet("QPushButton{ border-radius: 6;color: white;background-color: #34495e;}\n"
"QPushButton:pressed{ border-radius: 6;color: white;background-color: #517382;}")
        self.btn_echo.setObjectName("btn_echo")
        self.btn_file = QtWidgets.QPushButton(Dialog)
        self.btn_file.setGeometry(QtCore.QRect(560, 520, 121, 41))
        self.btn_file.setStyleSheet("QPushButton{ border-radius: 6;color: white;background-color: #34495e;}\n"
"QPushButton:pressed{ border-radius: 6;color: white;background-color: #517382;}")
        self.btn_file.setObjectName("btn_file")
        self.btn_emoji = QtWidgets.QPushButton(Dialog)
        self.btn_emoji.setGeometry(QtCore.QRect(400, 520, 121, 41))
        self.btn_emoji.setStyleSheet("QPushButton{ border-radius: 6;color: white;background-color: #34495e;}\n"
"QPushButton:pressed{ border-radius: 6;color: white;background-color: #517382;}")
        self.btn_emoji.setObjectName("btn_emoji")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(163, 5, 721, 41))
        self.label.setStyleSheet("#label{color: #34495e;font-size: 26px;}</string>")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btn_color = QtWidgets.QPushButton(Dialog)
        self.btn_color.setGeometry(QtCore.QRect(240, 520, 121, 41))
        self.btn_color.setStyleSheet("QPushButton{ border-radius: 6;color: white;background-color: #34495e;}\n"
"QPushButton:pressed{ border-radius: 6;color: white;background-color: #517382;}")
        self.btn_color.setObjectName("btn_color")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.lineEdit.setFocus()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "服务端"))
        self.btn_close.setText(_translate("Dialog", "关闭聊天"))
        self.label_2.setText(_translate("Dialog", "用户列表"))
        self.btn_sent.setText(_translate("Dialog", "发送"))
        self.btn_del.setText(_translate("Dialog", "刷新"))
        self.btn_echo.setText(_translate("Dialog", "文件接收"))
        self.btn_file.setText(_translate("Dialog", "选择文件"))
        self.btn_emoji.setText(_translate("Dialog", "表情"))
        self.label.setText(_translate("Dialog", "服务端"))
        self.btn_color.setText(_translate("Dialog", "颜色"))